In [27]:
import pandas as pd

In [35]:
df = pd.read_csv('books.csv')
df

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,6,11870085,11870085,16827462,226,525478817,9.780525e+12,John Green,2012.0,The Fault in Our Stars,...,2346404,2478609,140739,47994,92723,327550,698471,1311871,https://images.gr-assets.com/books/1360206420m...,https://images.gr-assets.com/books/1360206420s...
4,12,13335037,13335037,13155899,210,62024035,9.780062e+12,Veronica Roth,2011.0,Divergent,...,1903563,2216814,101023,36315,82870,310297,673028,1114304,https://images.gr-assets.com/books/1328559506m...,https://images.gr-assets.com/books/1328559506s...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,9925,86737,86737,3877968,52,1582349177,9.781582e+12,Mary Hoffman,2002.0,City of Masks,...,12048,13385,555,314,758,3154,4872,4287,https://images.gr-assets.com/books/1294870497m...,https://images.gr-assets.com/books/1294870497s...
1350,9937,13010211,13010211,18171867,22,1596435712,9.781596e+12,Caragh M. O'Brien,2012.0,Promised,...,11766,12884,1260,256,1098,3565,4392,3573,https://images.gr-assets.com/books/1330546217m...,https://images.gr-assets.com/books/1330546217s...
1351,9942,16074758,16074758,21869436,18,1442486597,9.781442e+12,"Abigail Haas, Abby McDonald",2013.0,Dangerous Girls,...,10439,12970,2631,203,553,2029,4567,5618,https://images.gr-assets.com/books/1356513050m...,https://images.gr-assets.com/books/1356513050s...
1352,9947,21393526,21393526,40690062,19,62320521,9.780062e+12,Maria Dahvana Headley,2015.0,Magonia,...,12510,13652,2910,577,1440,3881,4772,2982,https://images.gr-assets.com/books/1413479866m...,https://images.gr-assets.com/books/1413479866s...
1353,9955,13065327,13065327,18230950,25,802734375,9.780803e+12,Simone Elkeles,2013.0,Wild Cards,...,13954,15400,1514,406,965,3331,5038,5660,https://images.gr-assets.com/books/1420836321m...,https://images.gr-assets.com/books/1420836321s...

In [37]:
df = df.drop(['goodreads_book_id', 'best_book_id', 'work_id', 'original_title', 'language_code', 'image_url', 'small_image_url'] , axis = 1)
df

,book_id,books_count,isbn,isbn13,authors,original_publication_year,title,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
0,1,272,439023483,9.780439e+12,Suzanne Collins,2008.0,"The Hunger Games (The Hunger Games, #1)",4.34,4780653,4942365,155254,66715,127936,560092,1481305,2706317
1,2,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",1997.0,Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543
2,3,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,"Twilight (Twilight, #1)",3.57,3866839,3916824,95009,456191,436802,793319,875073,1355439
3,6,226,525478817,9.780525e+12,John Green,2012.0,The Fault in Our Stars,4.26,2346404,2478609,140739,47994,92723,327550,698471,1311871
4,12,210,62024035,9.780062e+12,Veronica Roth,2011.0,"Divergent (Divergent, #1)",4.24,1903563,2216814,101023,36315,82870,310297,673028,1114304
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,9925,52,1582349177,9.781582e+12,Mary Hoffman,2002.0,"City of Masks (Stravaganza, #1)",3.90,12048,13385,555,314,758,3154,4872,4287
1350,9937,22,1596435712,9.781596e+12,Caragh M. O'Brien,2012.0,"Promised (Birthmarked, #3)",3.77,11766,12884,1260,256,1098,3565,4392,3573
1351,9942,18,1442486597,9.781442e+12,"Abigail Haas, Abby McDonald",2013.0,Dangerous Girls,4.14,10439,12970,2631,203,553,2029,4567,5618
1352,9947,19,62320521,9.780062e+12,Maria Dahvana Headley,2015.0,"Magonia (Magonia, #1)",3.60,12510,13652,2910,577,1440,3881,4772,2982
1353,9955,25,802734375,9.780803e+12,Simone Elkeles,2013.0,"Wild Cards (Wild Cards, #1)",3.95,13954,15400,1514,406,965,3331,5038,5660

In [38]:
df.isna().sum()

book_id                       0
books_count                   0
isbn                         52
isbn13                       44
authors                       0
original_publication_year     3
title                         0
average_rating                0
ratings_count                 0
work_ratings_count            0
work_text_reviews_count       0
ratings_1                     0
ratings_2                     0
ratings_3                     0
ratings_4                     0
ratings_5                     0
dtype: int64

In [60]:
df.dropna(inplace=True)

In [61]:
hdf = df[df['title'].str.contains("harry potter", case=False)]
hdf

,book_id,books_count,isbn,isbn13,authors,original_publication_year,title,average_rating,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5
1,2,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",1997.0,Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479,4800065,75867,75504,101676,455024,1156318,3011543
6,18,376,043965548X,9.780440e+12,"J.K. Rowling, Mary GrandPr√©, Rufus Beck",1999.0,Harry Potter and the Prisoner of Azkaban (Harr...,4.53,1832823,1969375,36099,6716,20413,166129,509447,1266670
8,21,307,439358078,9.780439e+12,"J.K. Rowling, Mary GrandPr√©",2003.0,Harry Potter and the Order of the Phoenix (Har...,4.46,1735368,1840548,28685,9528,31577,180210,494427,1124806
9,23,398,439064864,9.780439e+12,"J.K. Rowling, Mary GrandPr√©",1998.0,Harry Potter and the Chamber of Secrets (Harry...,4.37,1779331,1906199,34172,8253,42251,242345,548266,1065084
10,24,332,439139600,9.780439e+12,"J.K. Rowling, Mary GrandPr√©",2000.0,Harry Potter and the Goblet of Fire (Harry Pot...,4.53,1753043,1868642,31084,6676,20210,151785,494926,1195045
11,25,263,545010225,9.780545e+12,"J.K. Rowling, Mary GrandPr√©",2007.0,Harry Potter and the Deathly Hallows (Harry Po...,4.61,1746574,1847395,51942,9363,22245,113646,383914,1318227
12,27,275,439785960,9.780440e+12,"J.K. Rowling, Mary GrandPr√©",2005.0,Harry Potter and the Half-Blood Prince (Harry ...,4.54,1678823,1785676,27520,7308,21516,136333,459028,1161491
96,422,76,545044251,9.780545e+12,J.K. Rowling,1998.0,"Harry Potter Boxset (Harry Potter, #1-7)",4.74,190050,204125,6508,1105,1285,7020,30666,164049
613,3753,6,439827604,9.780440e+12,J.K. Rowling,2005.0,"Harry Potter Collection (Harry Potter, #1-6)",4.73,24618,26274,882,203,186,946,3891,21048
1036,7018,42,042519891X,9.780425e+12,David Colbert,2001.0,The Magical Worlds of Harry Potter: A Treasury...,3.96,13820,15145,267,329,1125,3766,3593,6332
1266,9048,5,043932162X,9.780439e+12,J.K. Rowling,2001.0,Harry Potter Schoolbooks Box Set: Two Classic ...,4.40,10736,11732,185,106,304,1548,2595,7179

In [62]:
sorted_hdf = hdf.sort_values(by='books_count', ascending=False)
best_selling = sorted_hdf.iloc[0]['title']
print(best_selling , ', number of sales:' , sorted_hdf.iloc[0]['books_count'])

Harry Potter and the Sorcerer's Stone (Harry Potter, #1) , number of sales: 491

In [63]:
avg_rating = hdf['average_rating'].sum()/len(hdf)
avg_rating

4.482727272727273